{{- include "common.deployment" (list . .Values .Values.autoscaling .Values.serviceAccount "helm-template.deployment") }}

{{- define "helm-template.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{- include "common.container" (append . "helm-template.container") | nindent 8 }}
{{- end }}

{{- define "helm-template.container" -}}
{{- end }}
